import { useTypedTranslation } from "@/hooks/useTypedTranslation";
import TreeSideBar from "@/components/treeSideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { t } = useTypedTranslation();

  return (
    <div className="flex min-h-screen">
      <div
        className={`fixed top-0 h-screen w-[250px] mt-30 ${t("dir") === "rtl" ? "left-0" : "right-0"
          }`}
      >
        <TreeSideBar />
      </div>

      {/* المحتوى الرئيسي */}
      <div className={`flex-1 overflow-scroll px-4 md:px-6 ${t("dir") === "rtl" ? "ml-[250px]" : "mr-[250px]"}`}>
        {children}
      </div>

    </div>
  );
}
