import TreeSideBar from "@/components/treeSideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen">
      {/* السايدبار الثابت */}
      <div className="fixed left-0 top-0 h-screen w-[250px] mt-30">
        <TreeSideBar />
      </div>
      
      {/* المحتوى الرئيسي */}
      <div className="flex-1 ml-[250px]">
        {children}
      </div>
    </div>
  );
}