import { useTypedTranslation } from "@/hooks/useTypedTranslation";
import TreeSideBar from "@/components/treeSideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { t } = useTypedTranslation();

  return (
    <div className="flex min-h-screen">
      {/* السايدبار الثابت */}
      <div
        className={`fixed top-0 h-screen w-[250px] mt-30 ${t("dir") === "rtl" ? "left-0" : "right-0"
          }`}
      >
        <TreeSideBar />
      </div>

      {/* المحتوى الرئيسي */}
      <div
        className={`flex-1 ${t("dir") === "rtl" ? "ml-[200px]" : "mr-[200px] overflow-scroll"
          }`}
      >
        {children}
      </div>
    </div>
  );
}
