import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ReactQueryProvider from "@/providers/reactQuertProvider";
import HeroUiProvider from "@/providers/HerouiProvider";
import { getLocale, getTranslations } from "next-intl/server";
import RootLocaleLayout from "@/providers/NextIntlProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import Home from "./";
import ReduxProvider from "@/providers/reduxProvider";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const t = await getTranslations();
	return (
		<html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body
				suppressHydrationWarning
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#fafafa]`}
			>
				<NextTopLoader
					color="#16C47F"
					initialPosition={0.08}
					crawlSpeed={200}
					height={5}
					crawl={true}
					showSpinner={true}
					easing="ease"
					speed={200}
					shadow="0 0 10px #16C47F,0 0 5px #16C47F"
					template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
					zIndex={1600}
					showAtBottom={false}
				/>

				<SidebarProvider>
					<RootLocaleLayout>
						<ReactQueryProvider>
							<HeroUiProvider>
								<ReduxProvider>
									{children}
									<Toaster position="top-right" />
								</ReduxProvider>
							</HeroUiProvider>
						</ReactQueryProvider>
					</RootLocaleLayout>
				</SidebarProvider>
			</body>
		</html>
	);
}
